// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class DeathSystemDeathEventHandler {
        
        public Health SourceEntity;
        
        private test.DeathEvent _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private string FormatStringAction29_Result = default( System.String );
        
        private object ActionNode30_message = default( System.Object );
        
        private UnityEngine.GameObject ActionNode26_gameObject = default( UnityEngine.GameObject );
        
        private float ActionNode26_time = default( System.Single );
        
        public test.DeathEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // FormatStringAction
            while (this.DebugInfo("8c69d3e8-48ec-4ca0-b56c-457348fa1617","838f68ef-fe64-498b-b328-f548ed8aa45b", this) == 1) yield return null;
            FormatStringAction29_Result = string.Format(@"{0} got rekt!", SourceEntity.name);
            ActionNode30_message = FormatStringAction29_Result;
            // ActionNode
            while (this.DebugInfo("838f68ef-fe64-498b-b328-f548ed8aa45b","d72f7fea-9f22-4275-b7d0-76e1fecf4b8c", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode30_message);
            ActionNode26_gameObject = SourceEntity.gameObject;
            // ActionNode
            while (this.DebugInfo("d72f7fea-9f22-4275-b7d0-76e1fecf4b8c","559a280a-52be-4fde-8a8f-40f9a23f8cc6", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject
            uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject(ActionNode26_gameObject, ActionNode26_time);
            yield break;
        }
    }
}
