// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemGameReadyHandler {
        
        public MenuComponent Group;
        
        private uFrame.Kernel.GameReadyEvent _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private bool BoolNode44 = false;
        
        public uFrame.Kernel.GameReadyEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // SetVariableNode
            while (this.DebugInfo("26938b8b-41cf-4f56-9d90-e03bf210267a","874bb287-05ce-4206-9a2b-cf4ec3a0a1ef", this) == 1) yield return null;
            Group.gameObject.active = (System.Boolean)BoolNode44;
            yield break;
        }
    }
}
