// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemMenuToggleEventHandler {
        
        public MenuComponent Group;
        
        private test.MenuToggleEvent _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private bool ActionNode45_value = default( System.Boolean );
        
        private bool ActionNode45_Result = default( System.Boolean );
        
        public test.MenuToggleEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode45_value = Group.gameObject.active;
            // ActionNode
            while (this.DebugInfo("6b5662b6-0eda-4500-88ab-352311c0d5bf","248a95d8-d126-4c43-b29a-4e67b4b3f313", this) == 1) yield return null;
            // Visit ExampleScript.toggle
            ActionNode45_Result = ExampleScript.toggle(ActionNode45_value);
            // SetVariableNode
            while (this.DebugInfo("248a95d8-d126-4c43-b29a-4e67b4b3f313","26938b8b-41cf-4f56-9d90-e03bf210267a", this) == 1) yield return null;
            Group.gameObject.active = (System.Boolean)ActionNode45_Result;
            yield break;
        }
    }
}
