// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class MenuSystemMenuToggleEventHandler {
        
        public MenuComponent Group;
        
        private test.MenuToggleEvent _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private bool ActionNode38_value = default( System.Boolean );
        
        private bool BoolNode40 = false;
        
        private bool BoolNode41 = true;
        
        public test.MenuToggleEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode38_value = Group.gameObject.active;
            // ActionNode
            while (this.DebugInfo("6b5662b6-0eda-4500-88ab-352311c0d5bf","8cde595f-6926-4379-a755-feb41fa9d45a", this) == 1) yield return null;
            // Visit uFrame.ECS.Actions.Comparisons.IsTrue
            uFrame.ECS.Actions.Comparisons.IsTrue(ActionNode38_value, ()=> { System.StartCoroutine(ActionNode38_yes()); }, ()=> { System.StartCoroutine(ActionNode38_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode38_yes() {
            // SetVariableNode
            while (this.DebugInfo("8cde595f-6926-4379-a755-feb41fa9d45a","62523bc0-3f1b-4182-b2ce-3eceaf96df99", this) == 1) yield return null;
            Group.gameObject.active = (System.Boolean)BoolNode40;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode38_no() {
            // SetVariableNode
            while (this.DebugInfo("62523bc0-3f1b-4182-b2ce-3eceaf96df99","eeded012-68f5-46fb-991a-9a0233a21f9b", this) == 1) yield return null;
            Group.gameObject.active = (System.Boolean)BoolNode41;
            yield break;
        }
    }
}
