// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(2)]
    [uFrame.Attributes.uFrameIdentifier("a618bcaf-b218-4724-b91f-c2c7e14e4bbc")]
    public partial class Health : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _HealthValue;
        
        private Subject<PropertyChangedEvent<Int32>> _HealthValueObservable;
        
        private PropertyChangedEvent<Int32> _HealthValueEvent;
        
        public override int ComponentId {
            get {
                return 2;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> HealthValueObservable {
            get {
                return _HealthValueObservable ?? (_HealthValueObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 HealthValue {
            get {
                return _HealthValue;
            }
            set {
                SetHealthValue(value);
            }
        }
        
        public virtual void SetHealthValue(Int32 value) {
            SetProperty(ref _HealthValue, value, ref _HealthValueEvent, _HealthValueObservable);
        }
    }
}
