// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    
    
    public partial class NewGroupNodeGroup : ReactiveGroup<NewGroupNode> {
        
        private IEcsComponentManagerOf<Health> _HealthManager;
        
        private int lastEntityId;
        
        private Health Health;
        
        public IEcsComponentManagerOf<Health> HealthManager {
            get {
                return _HealthManager;
            }
            set {
                _HealthManager = value;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<UniRx.IObservable<int>> Install(uFrame.ECS.APIs.IComponentSystem componentSystem) {
            HealthManager = componentSystem.RegisterComponent<Health>();
            yield return HealthManager.CreatedObservable.Select(_=>_.EntityId);;
            yield return HealthManager.RemovedObservable.Select(_=>_.EntityId);;
        }
        
        public override bool Match(int entityId) {
            lastEntityId = entityId;
            if ((Health = HealthManager[entityId]) == null) {
                return false;
            }
            return true;
        }
        
        public override NewGroupNode Select() {
            var item = new NewGroupNode();;
            item.EntityId = lastEntityId;
            item.Health = Health;
            return item;
        }
    }
}
